### ISSUE TITLE
RuntimeError: Create window failed: Renderer does not support display.

### ISSUE THREAD

**Issue by xzhuzhu** [Rabbit-Hu/sapienipc-exp#3]
Hi, when I am running  example, I have the following error：
 the Traceback (most recent call last):
  File "/home/zl/sapienipc-exp/examples/example_peg.py", line 303, in <module>
    viewer = Viewer()
  File "/home/zl/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/sapien/utils/viewer/viewer.py", line 67, in __init__
    self.window = RenderWindow(*resolution, self.shader_dir)
RuntimeError: Create window failed: Renderer does not support display.
corrupted size vs. prev_size in fastbins
Aborted
How can I fix it, thanks.

**Comment by GeorgeWuzy** [comment]
Hi, I have the same bug, have you fix it?

**Comment by 15101051** [comment]
Are you running it on a remote headless server? You can try using display tools like X forwarding to display it.
