### ISSUE TITLE
RuntimeError: Failed to load the shared library '/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so'

### ISSUE THREAD

**Issue by XiaohangShi2000** [Rabbit-Hu/sapienipc-exp#4]
Excuse me, when I try to run the example_peg.py, the following error occurred: 
```bash
Traceback (most recent call last):
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 2494, in load_dll
    dll = ctypes.CDLL(dll_path, winmode=0)
  File "/home/xiaohang_shi/miniconda3/envs/mani_vitac/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xiaohang_shi/miniconda3/envs/mani_vitac/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaohang_shi/Project/sapienipc-exp/examples/example_peg.py", line 28, in <module>
    wp.init()
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 4102, in init
    runtime = Runtime()
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 1907, in __init__
    self.core = self.load_dll(warp_lib)
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 2498, in load_dll
    raise RuntimeError(f"Failed to load the shared library '{dll_path}'")
RuntimeError: Failed to load the shared library '/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so'
```
It seems to be that in my virtual environment's libstdc++.so.6, the 'GLIBCXX_3.4.30' is missing.
Could you please tell me how to fix it? Thanks!

**Comment by YuyangLee** [comment]
Hi, I met the same error. I tried to remove the original symlink at `/home/USERNAME/anaconda3/envs/mani_vitac/lib/libstdc++.so.6`, then re-create the symlink to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`. It worked for me, so maybe have a try :D

**Comment by XiaohangShi2000** [comment]
@YuyangLee Thanks. I have solved the problem using the same method as you last week.
